#!/bin/bash

xrandr --output HDMI-0 --primary
tint2 &
emerald &
if [ -f /home/$USER/.config/compiz-desktop/startup ]; then
echo 'exists' > /home/$USER/compiz
source /home/$USER/.config/compiz-desktop/startup
else
echo 'not exist' > /home/$USER/compiz
fi
exec dbus-launch compiz --replace ccp
